sudo: required
before_install:
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# install a newer version cmake
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  
  # Go to the Root directory  
  - cd ..

# Build steps
script:
  - lsb_release -a # os version
  - apt search protobuf
  - protoc --version
  - find /usr/ -iname 'protoc'
  - mkdir build
  - cd build
  - ${DEPS_DIR}/cmake/bin/cmake .. && make