sudo: required
before_install:
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler
  - sudo apt-get install -y cmake
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make