// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "webservice_server.h"

std::string webservice_server::echo(const std::string &text) {
  return "Hi, " + text;
}

int webservice_server::add(int a, int b) { return a + b; }
